javac^
 main\com\teamalfa\blindvirologists\agents\genetic_code\*.java^
 main\com\teamalfa\blindvirologists\agents\virus\*.java^
 main\com\teamalfa\blindvirologists\agents\*.java^
 main\com\teamalfa\blindvirologists\city\fields\*.java^ 
 main\com\teamalfa\blindvirologists\city\*.java^
 main\com\teamalfa\blindvirologists\equipments\*.java^
 main\com\teamalfa\blindvirologists\city\fields\active_equipments\*.java^
 main\com\teamalfa\blindvirologists\tun_handler\*.java^
 main\com\teamalfa\blindvirologists\virologist\*.java^
 main\com\teamalfa\blindvirologists\*.java